version: '3'

services:
  web-router:
    build: 
      context: .
      args:
        landscape: test
    read_only: true
    ports:
      - 80:80
      - 443:443
    #restart: always
    environment:
      - LANDSCAPE=test
      - ALLOW_DOCKER_NETS=true
