AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Prefix:
    Type: String
    Default: "web2cloud-test"
  Stage:
    Type: String
    Default: "test"
  Tag:
    Type: String
    Default: "9035b0c7"
    #Default: "latest"
  DesiredCapacity:
    Type: Number
    Default: '1'
    Description: Number of instances to launch in your ECS cluster.
  MaxSize:
    Type: Number
    Default: '1'
    Description: Maximum number of instances that can be launched in your ECS cluster.
  PublicAlbAcmCertificate:
    Description: '[ Optional ] The AWS Certification Manager certificate ARN for the ALB certificate - this certificate should be created in the region you wish to run the ALB and must reference the WordPress domain name you use below.'
    Type: String
    Default: ''
Conditions:
  IsTargetGroup443: !Not [ !Equals [ '', !Ref "PublicAlbAcmCertificate" ] ]
Resources:
  taskdefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Join ['', [!Ref 'AWS::StackName', -bufe]]
      ContainerDefinitions:
      - Name: bufe-buedu
        Cpu: '10'
        Essential: 'true'
        # uncomment the following if we can make the root file system read-only
        #ReadonlyRootFilesystem: 'true'
        #Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}:${Tag}"
        Image: 
          "Fn::Join": 
            - ':' 
            -
              - "Fn::ImportValue": !Sub "${Prefix}-container-repository-uri"
              - !Ref 'Tag'
        Memory: '300'
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: 
              "Fn::ImportValue": !Sub "${Prefix}-${Stage}-logs-group"
            awslogs-region: !Ref 'AWS::Region'
            awslogs-stream-prefix: bufe-buedu
        Environment:
          - Name: LANDSCAPE
            Value: syst
          - Name: LOG_LEVEL
            Value: warn
          - Name: ROBOTS_TXT
            Value: /home/robots.txt.test
          - Name: BACKEND_REDIRECT
            Value: "www-syst.bu.edu"
          - Name: BACKEND_W3_CONTENT
            Value: "www-syst.bu.edu:80"
          - Name: BACKEND_WP_APP
            Value: "www-syst.bu.edu:80"
          - Name: BACKEND_WP_CONTENT
            Value: "www-syst.bu.edu:80"
          - Name: BACKEND_WP_APP2
            Value: "www-syst.bu.edu:80"
          - Name: BACKEND_WP_CONTENT2
            Value: "www-syst.bu.edu:80"
          - Name: BACKEND_PHPBIN
            Value: "www-syst.bu.edu:80"
          - Name: BACKEND_DBIN
            Value: "www-syst.bu.edu:80"
          - Name: BACKEND_W3_MEDIA
            Value: "www-syst.bu.edu:80"
          - Name: BACKEND_DJANGO
            Value: "www-syst.bu.edu:80"
          - Name: BACKEND_DJANGO2
            Value: "www-syst.bu.edu:80"
          - Name: BACKEND_DEGREE_ADVICE
            Value: "www-syst.bu.edu:80"
          - Name: RELEASE
            Value: 20170829a
        PortMappings:
          - ContainerPort: 80
          - ContainerPort: 443
  service443:
    Condition: IsTargetGroup443
    Type: AWS::ECS::Service
    Properties:
      Cluster: 
        "Fn::ImportValue": !Sub "${Prefix}-ecscluster-ref"
      DesiredCount: !Ref 'DesiredCapacity'
      LoadBalancers:
      - ContainerName: "bufe-buedu"
        ContainerPort: '443'
        TargetGroupArn: 
          "Fn::ImportValue": !Sub "${Prefix}-targetgroup443-arn"
      Role: 
        "Fn::ImportValue": !Sub "${Prefix}-container-role"
      TaskDefinition: !Ref 'taskdefinition'
  service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: 
        "Fn::ImportValue": !Sub "${Prefix}-ecscluster-ref"
      DesiredCount: !Ref 'DesiredCapacity'
      LoadBalancers:
      - ContainerName: "bufe-buedu"
        ContainerPort: '80'
        TargetGroupArn: 
          "Fn::ImportValue": !Sub "${Prefix}-targetgroup80-arn"
      Role:
        "Fn::ImportValue": !Sub "${Prefix}-container-role"
      TaskDefinition: !Ref 'taskdefinition'
Outputs:
  ecsservice:
    Value: !Ref 'service'
  ecsservice443:
    Condition: IsTargetGroup443
    Value: !Ref 'service443'
  taskdef:
    Value: !Ref 'taskdefinition'
